[package]
name = "cosi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
derive_more = { version = "1.0.0", features = ["display", "error", "from"] }
log = "0.4.22"
mysql = "25.0.1"
serde = "1.0.209"
